export const terms = [
  {
    heading: "Eligibility",
    content:
      "You represent, acknowledge and agree that you are at least 18 years of age, and that: (a) all registration information that you submit is truthful and accurate, (b) you will maintain the accuracy of such information, and (c) your use of the Website and Services offered through this Website do not violate any applicable law or regulation. Your Account may be terminated without warning if we at our discretion, believe that you are under the age of 18 or that you are not complying with any applicable laws, rules or regulations. If you are below 18 and you wish to use the Website, you must get consent from your parents or guardian before doing so. You hereby expressly acknowledge and agree that you yourself and not CarLand will be liable for your losses, damages etc. (whether direct or indirect)caused by an unauthorized use of your Account. Notwithstanding the foregoing,you may be liable for the losses of CarLand or others due to such unauthorized use. An Account holder is sometimes referred to herein as a “Registered User”.",
  },
  {
    heading: "REGISTRATION AND ACCOUNT",
    content: `1. You realise and agree that in order to register on the Site, You must first meet the criteria of this Clause 3 and provide Your Registration Data. 2. You are responsible for making sure that the registration information you supply is true, accurate, current, and full. For any false, erroneous, outdated, or wrong registration data that You give, We will have no responsibility.
      3. You alone are in charge of protecting the privacy of Your Registration Data, and you'll be held accountable for any acts taken under Your Account, whether you took the initiative or someone else did. Your Account cannot be given away, sold, or delegated to another person. We are not responsible for any damages You could suffer if someone else uses your password or account, either knowingly or unknowingly. 4. If We have reason to suspect that the Registration Data or any other information you have provided is untrue or inaccurate, that Your Account's security has been compromised in any way, or for any other reason We may deem just or equitable, We reserve the right to suspend or terminate Your Account with immediate effect and for an indefinite period. 5. When using the Services, you agree to abide by all relevant laws, and you may only do so for legal reasons. (e.g., no transport of unlawful or hazardous materials). You promise not to offend, irritate, or inconvenience anybody else while using the Services. To access or use the Services, you could sometimes be required to provide identification, and if you decline, you risk having your access or use of the Services revoked.`,
  },
  {
    heading: "PAYMENT",
    content:
      "1. At the start of each ride, CarLand will give you an estimate of the total ride fee. According to the rules outlined in this document, the customer must pay the real Total journey price that is shown at the conclusion of the journey.2. You are aware of and agree to pay CarLand the whole ride fee, including any relevant taxes, as soon as the ride is complete or even before the ride, as shown in advance on the mobile application. You must pay CarLand right away once the journey is over if the actual cost of the trip differs from the estimate.3 You understand that this Additional Fee will be included in the receipt of the Total Ride Fee and agree to pay it.4. You must pay 20% of the cancellation fee, which will be deducted from the total ride fee that you will be reimbursed for.5 CarLand will provide you a receipt for the total ride fee you owe at the conclusion of the ride; nevertheless, bills from CarLand will be sent to the email address you have on file.6. You recognise that any relevant taxes are a part of the total ride fee and agree to pay them.7. You may choose to pay the whole ride fee using one of the payment methods provided by CarLand on the website in addition to paying cash to the driver after the ride is over.8. To process payment of the Total Ride Fee, you will be required to provide relevant payment information, including Credit Card, Debit Card, and Net Banking details (Card Details). You authorise CarLand and an entity authorised by CarLand to provide payment gateway/processor services (Payment Processor) to access the Card details in order to process the Total Ride Fee payment.9. The Total Ride Fee paid by You is final and non-refundable, subject to these Customer Terms, unless CarLand determines otherwise. Any money you have paid will be returned to you by CarLand to the same account from which it was taken if it is completely or partly refundable for any reason.10 You and the appropriate Payment Processor must work together to find a solution to any problem with payment processing that is not the result of a mistake or flaw with the Application.11. You agree and acknowledge that CarLand shall recover any outstanding funds payable by You for Ride(s) in respect of which Total Ride Fee has not been paid, and that in the event of a default or failure to pay the Total Ride Fee by You for any reason, (i) CarLand may prevent You from booking a new Ride through the Application until the Outstanding Total Ride Fee in respect of the Previous Ride(s) has been paid by You, (ii) You agree and acknowledge that CarLand shall recover any Outstanding Amount ",
  },
];
